const commonIngredients = [
  "Salt", "Sugar", "Flour", "Eggs",
  "Milk", "Butter", "Cheese", "Bread",
  "Chicken", "Beef", "Pork", "Fish",
  "Rice", "Pasta", "Potatoes",
  "Tomatoes", "Onions", "Garlic",
  "Peppers", "Carrots", "Lettuce",
  "Spinach", "Broccoli",
  "Cauliflower", "Mushrooms", "Corn",
  "Green beans", "Peas", "Lentils",
  "Chickpeas", "Kidney beans",
  "Black beans", "Soy sauce",
  "Vinegar", "Olive oil",
  "Vegetable oil", "Mayonnaise",
  "Ketchup", "Mustard", "Hot sauce",
  "BBQ sauce", "Salsa", "Honey",
  "Maple syrup", "Jelly",
  "Peanut butter", "Almonds",
  "Walnuts", "Pecans", "Cashews",
  "Hazelnuts", "Pistachios",
  "Macadamia nuts", "Chocolate chips",
  "Cocoa powder", "Baking soda",
  "Baking powder", "Vanilla extract",
  "Cinnamon", "Nutmeg", "Ginger",
  "Curry powder", "Chili powder",
  "Paprika", "Cumin", "Turmeric",
  "Bay leaves", "Thyme", "Rosemary",
  "Sage", "Oregano", "Basil", "Dill",
  "Parsley", "Salt and pepper",
  "Brown sugar", "Powdered sugar",
  "Confectioner's sugar", "Molasses",
  "Corn syrup", "Flavor extracts",
  "Cake mix", "Pancake mix", "Syrup",
  "Breadcrumbs", "Crackers", "Chips",
  "Popcorn", "Cookies", "Cereal",
  "Oatmeal", "Granola", "Yogurt",
  "Ice cream", "Frozen vegetables",
  "Frozen fruit", "Frozen dinners"
];

export default commonIngredients;
