const commonAllergicIngredients = [
  "Peanuts",
  "Tree Nuts",
  "Milk",
  "Eggs",
  "Fish",
  "Shellfish",
  "Wheat",
  "Soy",
  "Gluten",
  "Sesame",
  "Sulfites",
  "Mustard",
  "Celery",
  "Lupin",
  "Mollusks",
  "Corn",
  "Sulfur dioxide",
  "Chocolate",
  "Citrus fruits",
  "Kiwi",
  "Tomatoes",
  "Berries",
  "Bananas",
  "Avocado",
  "Coconut",
  "Garlic",
  "Onions",
  "Bell peppers",
  "Artificial food colorings",
  "Artificial sweeteners",
  "Monosodium glutamate (MSG)",
  "Caffeine",
  "Alcohol",
  "Honey",
  "Soy sauce",
  "Gelatin",
  "Yeast",
  "Oats",
  "Barley",
  "Rye",
  "Rice",
  "Quinoa",
  "Cashews",
  "Almonds",
  "Hazelnuts",
  "Walnuts",
  "Pistachios",
  "Macadamia nuts",
  "Brazil nuts",
  "Pecans",
  "Pine nuts",
  "Sunflower seeds",
  "Poppy seeds",
  "Chia seeds",
];

export default commonAllergicIngredients;